[package]
name = "aptos-event-notifications"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]

aptos-types = { workspace = true}
anyhow = { workspace = true }
